# Generated by Django 5.1.6 on 2025-05-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_criancas_pagantes', models.IntegerField()),
                ('valor_por_crianca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_adultos_pagantes', models.IntegerField()),
                ('valor_por_adulto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=50)),
                ('nota_fiscal', models.BooleanField(default=False)),
                ('recibo', models.BooleanField(default=False)),
                ('agencia', models.BooleanField(default=False)),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('numero_previsto_criancas', models.IntegerField()),
                ('numero_adultos_cortesia', models.IntegerField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
                ('clima', models.CharField(max_length=100)),
                ('serie_alunos', models.CharField(max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitores_fazendinha', models.TextField()),
                ('monitores_free', models.TextField()),
                ('guia_fazendinha', models.CharField(max_length=255)),
                ('guias_free', models.TextField()),
                ('historico_passeio', models.TextField()),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escola')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visita')),
            ],
        ),
    ]
