# Generated by Django 5.1.6 on 2025-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escola_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='clima',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visita',
            name='periodo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='serie_alunos',
            field=models.CharField(max_length=50),
        ),
    ]
