# Generated by Django 5.1.6 on 2025-05-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_visita_clima_alter_visita_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='guias_free',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='historico_passeio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
