# Generated by Django 5.2.1 on 2025-05-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_monitor_guias_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='feita',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.escola'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visita'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.escola'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.escola'),
        ),
    ]
