# Generated by Django 5.2.1 on 2025-05-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visita_feita_alter_monitor_escola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
