# Generated by Django 5.2.1 on 2025-05-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pagamento_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='escola',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='escola',
            name='responsavel',
            field=models.CharField(max_length=100),
        ),
    ]
