# Generated by Django 5.2.1 on 2025-05-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_escola_bairro_alter_escola_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='bairro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escola',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='escola',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escola',
            name='responsavel',
            field=models.CharField(max_length=255),
        ),
    ]
