# Generated by Django 5.2.1 on 2025-05-17 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_escola_bairro_alter_escola_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visita'),
        ),
    ]
