# Generated by Django 5.2.1 on 2025-05-25 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pagamento_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='visita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.visita'),
            preserve_default=False,
        ),
    ]
