# Generated by Django 5.2.4 on 2025-09-05 02:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pagamento_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCadastroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_sugerida', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.visita'),
        ),
    ]
