# Generated by Django 5.2.1 on 2025-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_precadastrovisita_alter_pagamento_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastrovisita',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=18),
        ),
    ]
