# Generated by Django 5.2.1 on 2025-09-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_precadastrovisita_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastrovisita',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro')], default='pix', max_length=10),
        ),
        migrations.AddField(
            model_name='precadastrovisita',
            name='numero_previsto_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='precadastrovisita',
            name='numero_previsto_criancas',
            field=models.IntegerField(default=0),
        ),
    ]
