# Generated by Django 5.2.4 on 2025-09-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_precadastrovisita_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCadastroEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=18)),
                ('senha', models.CharField(max_length=128)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
