# Generated by Django 5.2.4 on 2025-10-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_precadastrovisita_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precadastrovisita',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='precadastrovisita',
            name='data_envio',
        ),
        migrations.RemoveField(
            model_name='precadastrovisita',
            name='escola',
        ),
        migrations.AddField(
            model_name='precadastroescola',
            name='telefone',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='precadastrovisita',
            name='forma_pagamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='precadastrovisita',
            name='numero_previsto_adultos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='precadastrovisita',
            name='numero_previsto_criancas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='precadastrovisita',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
