# Generated by Django 5.2.4 on 2025-10-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_precadastrovisita_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadastrovisita',
            name='cnpj',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
    ]
