# Generated by Django 5.2.4 on 2025-10-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_precadastrovisita_cnpj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreCadastroEscola',
        ),
        migrations.DeleteModel(
            name='PreCadastroVisita',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='data',
            new_name='data_sugerida',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='clima',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='serie_alunos',
        ),
        migrations.AddField(
            model_name='visita',
            name='agencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix')], default='dinheiro', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='numero_previsto_adultos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='numero_previsto_criancas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='responsavel',
            field=models.CharField(default='nao informado', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='periodo',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10),
        ),
    ]
