# Generated by Django 5.2.4 on 2025-10-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_precadastroescola_delete_precadastrovisita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='cep',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='cidade',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='estado',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
