# Generated by Django 5.2.4 on 2025-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_escola_cep_escola_cidade_escola_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20),
        ),
    ]
