# Generated by Django 5.2.4 on 2025-10-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_visita_feedback_visita_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='agencia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='periodo',
            field=models.CharField(choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], max_length=5),
        ),
    ]
