# Generated by Django 5.2.4 on 2025-10-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_visita_agencia_alter_visita_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
